# Denotes the schema for the configuration file
# of the rsvplist module
rsvplist.settings:
  type: config_object
  label: 'RSVP List Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content types RSVP Form can display only'
      sequence:
        type: string
        label: 'Content type'